### ISSUE TITLE
A "no-write" option for heimdal-history 

### ISSUE THREAD

**Issue by macrotex** [rra/krb5-strength#1]
It appears that there is no way to run `heimdal-history` without (potentially) updating the history database. 

It would be very helpful to have a "no-write" option that checks the history database but does not update it.

**Comment by rra** [comment]
Indeed, that would be useful, although as a workaround you can make a copy of the history and password length databases and then use the `-d` and `-S` flags.

**Comment by macrotex** [comment]
It's been a while and I could really use this feature. Is there anything I can do to push this feature addition forward?

**Comment by rra** [comment]
Sorry this took me so long. Had some prerequisite work to do to modernize this package and prepare for a new release. A new release with this change should be coming shortly.

**Comment by macrotex** [comment]
What are the chances that the new release will make it into bullseye?

**Comment by rra** [comment]
Basically 100%.
